name: Deploy React App

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - run: npm ci

            - run: npm run lint

            - run: npm run build

            - name: Deploy to GitHub Pages
              if: github.ref == 'refs/heads/main'
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist

            - name: Post Deployment Cleanup
              if: github.ref == 'refs/heads/main'
              run: |
                  echo "Deployment completed successfully."
                  echo "You can view your site at https://peluso.photos/"

            - name: Notify Deployment Success
              if: github.ref == 'refs/heads/main'
              run: |
                  echo "Deployment to GitHub Pages was successful!"
                  echo "You can view your site at https://peluso.photos/"

            - name: Notify Deployment Failure
              if: failure()
              run: |
                  echo "Deployment failed. Please check the logs for more details."
                  echo "You can view your site at https://peluso.photos/"
